### PR TITLE
Backport fixes from zubaxdoc.cls to uavcandoc.cls

### PR DESCRIPTION
**Pull request by clyde-johnston**
This PR fixes issue #35.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
The tables in the document have to be updated because now with the new default left skip behavior some of them should be amended with `[wide]` (those that are wide enough).

The doc should also be skimmed to look for formatting issues introduced by the switch to newer LaTeX.

I think we should also release a new version of the texer container but this is obviously out of the scope of this PR.

**Comment by clyde-johnston** [comment]
> I think we should also release a new version of the texer container but this is obviously out of the scope of this PR.

Opened issue [#9](https://github.com/UAVCAN/docker_toolchains/issues/9) in UAVCAN/docker_toolchains for this.

**Comment by clyde-johnston** [comment]
> The tables in the document have to be updated because now with the new default left skip behavior some of them should be amended with `[wide]` (those that are wide enough).
> 
> The doc should also be skimmed to look for formatting issues introduced by the switch to newer LaTeX.

This should be directed to the typographer. My quick scan of the document did not find any issues although tables 4.2 and 4.3 might be candidates for the [wide] option.

Also, some tables seem to have been included as images and thus to do not conform to the standard alignments. It might be better to change these to LaTeX tables.

**Comment by pavel-kirienko** [comment]
Okay. I looked through the doc and I think we need `[wide]` on tables 3.12, 3.14, 4.2, 4.3, 7.1, 7.5, 7.6, plus all tables generated by `render_dsdl.py` (they are raw `tabu`s so maybe they don't need fixing at all). Could you please update this PR accordingly?

**Comment by clyde-johnston** [comment]
> Could you please update this PR accordingly?

Done.

**Pull request merged**
